apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z3u2x3y6a-java-quarkus
  janus-idp.io/tekton: z3u2x3y6a-java-quarkus
  backstage.io/kubernetes-id: z3u2x3y6a-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z3u2x3y6a-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
